### ISSUE TITLE
Add us-east-1 (N Virginia) region

### ISSUE THREAD

**Issue by demeringo** [Boavizta/cloud-scanner#201]
## Problem

Missing US regions.

## Solution

Add us-east-1 at minima (N Virginia)

https://docs.aws.amazon.com/fr_fr/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

## Alternatives

Manage all regions in a file in a second step, see #197

**Comment by demeringo** [comment]
@bamthomas

**Comment by bamthomas** [comment]
:+1: 
Thanks @demeringo 
If I can help let me know!

**Comment by demeringo** [comment]
Thanks, @bamthomas. it should be ok by now for all US regions 👍

Just use latest version 0.2.2.
