### ISSUE TITLE
Add optional verbose output with the details of the calculation

### ISSUE THREAD

**Issue by demeringo** [Boavizta/cloud-scanner#333]
## Problem

Cloud scanner does not return details about the components that leads to a result.
Which prevent us to understand the impact of RAM vs CPU for example.

## Solution

Have an optional flag or parameter that add verbosity to the json output.

It should return the equivalent content (list of components and impacts) that are returne by the Boavizta API when used in verbose mode.

⚠ WARNING: It seems that in Boavizta API, The results of Verbose mode do not correspond to the instance,  but to the _entire_ server that host an instance. In verbose mode, no ratio is applied to the impacts of components (contrary to non-verbose API output where a ration corresponding to the number of instances per servers is applied before returning results).

See discussion in Boavizta API Q/A: https://github.com/Boavizta/boaviztapi/discussions/221

**Comment by demeringo** [comment]
We will do 2 things:
1. add a raw_data key to the cloud-scanner json output: It will _always_ contain the raw_output of Boavizta API. The rationale is that if API evolves, we benefit from or can parse an additional field that is not managed by cloud-scanner.
2. Add a verbose flag or parameter (default to false) to the cloud-scannner commands or routes. If active, it will trigger the verbose output of the Boavizta API (which we will retrieve in the new raw_data field.

**Comment by damienfernandes** [comment]
@demeringo amazing ! Thanks olivier
