### ISSUE TITLE
Estimate with Retro Action & Simulation

### ISSUE THREAD

**Issue by damienfernandes** [Boavizta/cloud-scanner#370]
## Problem

Feature: Retro action & simulation​
- Run asynchronously estimation of environemental impact​
- Simulate estimation of environemental impact with another referential or update of referential​

## Solution

Only deploy inventory scanner and store file result during performance shoot​ for example
Add feature in Cloudscaner to be able to simulate estimation of impact with that inventory history​

**Comment by demeringo** [comment]
Related to #352

**Comment by demeringo** [comment]
We should close this issue (because it was implemented in #352 and #505)
