### ISSUE TITLE
Aggregate impact values across all the resources when calling estimate on the CLI

### ISSUE THREAD

**Issue by jnioche** [Boavizta/cloud-scanner#456]
Calling `estimate` with the CLI returns the impacts values for each resource. It would be useful to also return an aggregate of all the counts to give an overview of the overall impact.

**Comment by demeringo** [comment]
We already have a build summary function that aggregaes impacts. 
At the moment it is only used when producing metrics but we could re-use it.

I image 2 possibilities:
- add the summary at the end of the json output (always)
- update cli flags or API route to retrieve only the summary
