### ISSUE TITLE
Mark next version post release with -SNAPSHOT

### ISSUE THREAD

**Issue by jnioche** [Boavizta/cloud-scanner#624]
## Bug description

The version in the cargo files is currently showing 3.1.0 which has already been released. 
What we should do instead if to move to the next version right after a release and suffix it with `-SNAPSHOT`
We should make this explicit in any documentation we have about the release process

**Comment by jnioche** [comment]
@demeringo is the release process documented anywhere?

**Comment by demeringo** [comment]
No it is not documented, but it The current semi manual release process involves:
- updating cloud scanner version in the cloud-scanner-cli cargo.toml https://github.com/Boavizta/cloud-scanner/blob/main/cloud-scanner-cli/Cargo.toml
- updating the version in cloud-scanner-lambda cargo.toml: https://github.com/Boavizta/cloud-scanner/blob/main/cloud-scanner-lambda/Cargo.toml
- updating the tag of the image in docker-compose (using the not-yet-published version that we declared just above)
- updating the changelog.md (mention this new version, move _unreleased_ entries under this new version)
- merge this changes to main
- create a github relase vX.Y.Z` (i.e. in practice, this tags main branch with the same version like 'vX.Y.Z`), I generally tick to create a related discution.
- publish the release (which triggers the build / publish of docker image in CI).

Sometimes, if I fear a breaking change, I publish and alpha or beta release, but generally not.

**Comment by demeringo** [comment]
And yes, I fully agree with adding systematically the  -SNAPSHOT tag to avoid confusion with published versions.

**Comment by jnioche** [comment]
thanks @demeringo , I copied your comments to 

https://github.com/Boavizta/cloud-scanner/wiki/Release-Process

to make it easier to find later

**Comment by jnioche** [comment]
@demeringo why not just rely on    

 _image: ghcr.io/boavizta/cloud-scanner-cli:latest_
 
 in docker-compose?
