### ISSUE TITLE
[QUESTION] are we getting dependencies from -lambda when building the Docker image

### ISSUE THREAD

**Issue by jnioche** [Boavizta/cloud-scanner#625]
## Bug description

The `Dockerfile` is at the root of the project, since we are interested in building a Docker image for the CLI only, shouldn't we move that file to _cloud-scanner-cli_ part of the project?

@demeringo aren't we getting the dependencies from _cloud-scanner-lambda_ when building at the root?

**Comment by demeringo** [comment]
Hi, you are right, but it seems that `cargo-chef` that we use in the `Dockerfile` can support a `--bin` option that allow to compile only the relevant dependancies for a specific bin.

In the current version of our Dockerfile, this option is **not** used everywhere (but it should according to the author): https://github.com/LukeMathWalker/cargo-chef/issues/273#issuecomment-2227013832
