### ISSUE TITLE
Upgrade to BoaviztAPI 1.3.3

### ISSUE THREAD

**Issue by jnioche** [Boavizta/cloud-scanner#633]
https://github.com/Boavizta/boaviztapi/

**Comment by demeringo** [comment]
We need to check with @da-ekchajzer if there were breaking changes in the API routes / parameters related to cloud (in which case we may have to regenerate a SDK).

Otherwise (if the change is only internal to the API or data returned) we should be able to swap it directly (in docker compose).

**Comment by jnioche** [comment]
Agreed. I would hope that the version number change reflects that the new version does not contain anything breaking. My initial tests with the latest image seem to show that it is running fine

**Comment by da-ekchajzer** [comment]
For information, the worklfow that was supposed to generate the sdk didn't succeed because benoit's email associated with pypi doesn't have the MFA. And because I'm stupid I deleted the workflow.

**Comment by demeringo** [comment]
Cool, thank you @da-ekchajzer.

@jnioche I should be able to update and publish the API SDK today and show API version in cloud scanner outputs(see #266 #265) before end of week. But if you prefer to release a version of cloud scanner right now, without waiting for this, no problem (Current cloud scanner tests pass when targetting the latest API).

**Comment by jnioche** [comment]
@demeringo no rush, we might as well include the API versions in the next release
