### ISSUE TITLE
Upgrade version of BoaviztAPI to 1.3.7 and adjust tests accordingly

### ISSUE THREAD

**Issue by jnioche** [Boavizta/cloud-scanner#643]
## Problem

Our tests fail because we are hitting the live version of the API on https://api.boavizta.org/, that version has changed

## Solution

We should ideally run a docker container locally so that we are not dependent on changes from api.boavizta.org
We should also change the version of the API in docker compose and upgrade the version of the client accordingly

**Comment by demeringo** [comment]
I think we should break this issue into 2:
- this issue to fix the tests (make them pass)
- a separate issue to find a better way to run the tests

Long story short, I did some exploaration with testcontainers and I do not find a trivial way to reuse a test container between multiple async tests. Maybe I am just missing something obvious.
https://github.com/Boavizta/cloud-scanner/blob/8228779ffd65bc328f08095ac6c28cf75c24a0a2/cloud-scanner-cli/src/boavizta_api_v1.rs#L349

As you said @jnioche there may be also different way to test against a container (either externaly to Rust or integrated with Cargo test) but 
But I would rather explore the differrent options separately from the pressing "fix the test" issue.

**Comment by jnioche** [comment]
created #645 to track the improvements to the tests
